megamod.user.js
Here's a fix for the issue I mentioned in #2 [here](https://github.com/aclist/kbin-megamod/pull/2#issuecomment-1604919347), it just adds a simple try...catch block to applySettings to catch any errors when loading mods
=> fix: Add try/catch to applySettings to prevent errored mods from stopping loading

megamod.css
Here's a fix for the issues with the modal's height changing when switching pages while docked, and for the width changing when opening a mod with a long description (I think, I couldn't reproduce the problem, but I believe I've prevented it from happening in the future.)
=> Prevent modal from changing size

mods/label.user.js
Will now respect kbin style selection (i.e., square or rounded borders). Code refactor and change to support safeGM because why not?
=> feature: respect kbin style options

mods/label.user.js
I made the CSS selector a bit stricter to prevent it from applying the tag to replies to OP's comments
=> Prevent OP label from showing on children of OP when collapsible comments is enabled

mods/fix-codeblocks/fix-codeblocks.json, mods/fix-codeblocks/fix-codeblocks.user.js
Added a mod that fixes a long-running issue with code blocks federated from Lemmy on /kbin. 
Lemmy includes extra `<span style="color:#323232;">` tags enclosing every line in their federated code blocks which /kbin just displays in plaintext. See [this comment](https://kbin.social/m/programming@programming.dev/t/623282/Implementing-Tic-Tac-Toe-with-170mb-of-HTML-no-JS#entry-comment-3548488) for an example.
This mod fixes that by removing those tags:
Before submission, verify that you checked the below. If complete, tick the box.
I'm a bit confused by manifest.json being in this mod-specific checklist, you might want to edit either the checklist or the documentation. The latter claims manifest.json is automated and I should only be submitting the mod's folder and no other files, so I'm …
=> [Mod] Fix code blocks

mods/fix-codeblocks/fix-codeblocks.json, mods/fix-codeblocks/fix-codeblocks.user.js
[example]: https://kbin.social/m/programming@programming.dev/t/726929/The-C-scope-resolution-operator-is-beautiful
This pull request resolves the issues seen in #237.
With these changes, the [example] brought up there works perfectly.
Specifically, the two issues that were made apparent in the [example] are
1. the mod determines erroneous tags by a specific color, but they can have any color.
2. the mod assumes there's one erroneous closing and one ending tag per line only, but there can be any number of them.
To make sure these can be restored correctly on teardown, the mod now preserves the original code and merely hides it, instead adding the fixed code to a new element. On teardown the new element is then simply deleted and the original one made visible again.
I've also fixed an issue …
=> (fix-codeblocks) Fixes in response to #237

mods/unsanitize_css/unsanitize_css.json, mods/unsanitize_css/unsanitize_css.user.js
Kbin currently allows magazines to declare custom CSS that is applied while viewing them, and users can also change the CSS of the site in their settings.
This behavior is currently bugged however. Any CSS defined this way gets HTML escaped, causing certain characters like > and & to be replaced with HTML escape codes. This causes any CSS rule that uses them to not actually work, causing confusion and imposing unnecessary limitations on what can be achieved.
Until kbin fixes this bug themselves, I've implemented this fix as a mod.
I doubt this has a lot of use on its own currently, especially with how underused CSS is on kbin in the first place. And anyone who tests their code wouldn't have CSS that needs this mod running on their magazine anyway. For user CSS, I recommend userstyles over …
=> [Mod] Unsanitize CSS (another kbin bugfix)

kes.user.js
This is a fix for the settings button not being injected anymore.
The issue occurs because Mbin renamed the `.kbin-container` class to `.mbin-container` in its latest version. The button was looking for the former specifically, now it checks both.
=> Settings Button Fix

mods/dropdown/dropdown.json, mods/dropdown/dropdown.user.js
The links in the dropdown were leading to 404 pages because mbin URLs are case sensitive and all lowercase, while this mod's links are capitalized. So I added a `toLowerCase()`.
=> [FIX] The (profile) dropdown mod's links weren't working

mods/hide_reputation/hide_reputation.json, mods/hide_reputation/hide_reputation.user.js
Mbin has added additional items to the menus where hide_reputation applies, but it was removing the reputation by an explicit index. Since the new items offset the intended one, this caused the wrong item to be removed.
I changed the logic so it uses the URL rather than an index. Might still change in the future, but it's far less likely.
=> [FIX] Improved hide_reputation's item selection logic so the right item gets hidden

mods/thread_delta/thread_delta.json, mods/thread_delta/thread_delta.user.js
The setting with the `state` key kept getting overridden by the mod getting turned on or off. I changed the key so it actually returns the expected value.
=> [FIX] thread_delta setting now returns the correct value.

mods/omni/omni.json, mods/omni/omni.user.js
The omnibar's meta key option wasn't working because of the `.mbin-container` issue. Now it works again.
=> [FIX] Omnibar meta key wasn't working

mods/improved_collapsible_comments/improved_collapsible_comments.json, mods/improved_collapsible_comments/improved_collapsible_comments.user.js
Some of the CSS from this mod was applied in cases where it shouldn't.
- The left border of the square avatar style was cut off because of the comment line removal CSS being too broad and applying to ALL divs inside the .comments element.
- On some profile pages where the bulk of the script didn't apply, especially in regards to microblog posts, it still pushed all replies to the left, killing the visual hierarchy. 
In this PR I fixed those two issues and also adjusted the description to be more truthful. It mentioned that comments can be collapsed by clicking on their header, but that feature didn't get implemented in the KES version.
=> [FIX] Collapsible Comments CSS was too broadly defined in some places

mods/notifications_panel/notifications_panel.json, mods/notifications_panel/notifications_panel.user.js
This mod had two issues.
1. The button for the notifications panel wasn't added. This was because of the `.mbin-container` change.
2. The contents didn't load, because the tokens for the mark as read and purge buttons weren't found and so an exception was thrown.
The two commits here fix those two issues.
=> [FIX] Notification panel failed to load

helpers/safegm.user.js
Adds a logger to provide more flexibility to scripts to  print meaningful info to the console.
Called as `log("some string")` and outputs as `[KES:callingFunction] [ISO8601 timestamp] some string`
=> [FEAT] add logger

mods/resize_text/resize_text.json, mods/resize_text/resize_text.user.js
Fixed a few issues with some of the options in this mod:
- The description claimed a reload would be required to turn the mod off, but that wasn't the case for me at all.
- The footer option didn't work because Mbin moved its "footer" to the sidebar where it's affected by the regular sidebar option. So I removed the option.
- The sort by option only applied to the icons in the sort bar, not the actual text.
- The notifications and the messages title were suffering from the `.mbin-container` issue.
=> [FIX] resize_text mod didn't work fully

kes.user.js, mods/timestamp/timestamp.user.js
Resolves multiple issues brought up in https://github.com/aclist/kbin-kes/issues/354:
- Mod required hard reload for teardown
The mod now makes a clone of the `timeago` elements and hides the original ones. On teardown, the clones are cleared and the original elements are made visible again. Their human readable timestamps continued updating in the background, so on teardown, the relative time delta is still accurate.
- Unnecessary recursion
Increments to the `timeago-id` parameter of `timeago` elements are silently ignored, and if a `timeago` element has already been cloned, the clone action is not propagated again.
- Update UTC/local time variant in place
If the user has changed their time setting preference while the mod is already on, the mod recursively updates existing timestamps to …
=> fix: timestamps

mods/hide_sidebar/hide_sidebar.json, mods/hide_sidebar/hide_sidebar.user.js
Adds an option to the `hide_sidebar` mod which allows hiding the subscription panel in the sidebar. While a native option to do this already exists, that one removes the panel entirely. This one simply hides it (like the other options in the mod), making the actual list still available for other functions and scripts to use.
=> feat(hide_sidebar): option to hide the subs panel

mods/hide_sidebar/hide_sidebar.json, mods/hide_sidebar/hide_sidebar.user.js
When the entire sidebar is hidden, the space it occupied is still left empty. This PR adds an option to have the main content expand to make use of the freed up space.
=> feat(hide_sidebar): expand content when sidebar is hidden

.eslintrc, mods/notifications_panel/notifications_panel.user.js
Updates the notification panel mod's button and header styling by using more readable internal Mbin theme variables that follow the look of buttons in the sidebar. Resolves https://github.com/aclist/kbin-kes/issues/414
=> fix: readable header styling

.eslintrc, helpers/safegm.user.js
- Adds `Log.Log`, `Log.Warn`, and `Log.Error` enums
- Call the log function as `log(<STRING>, <LOGLEVEL>)`, e.g., `log("Something went wrong", Log.Warn)`
=> feat: add more log levels and enums

.eslintrc, helpers/safegm.user.js, mods/remove_ads/remove_ads.js
This recycles the loading prompt used in the `remove_ads` mod into a more generic dialog.
The dialog creation function can be globally called via `makeLoader(id, text)`, where `id` corresponds to an element id to assign to the dialog, and `text` corresponds to some user-facing string to print while loading. All child elements of the dialog are prefixed with the id originally supplied as a parameter to this function.
The function returns a modal dialog that can be inserted into the tree somewhere. During creation, it also leverages `safeGM("addStyle")` to append a named stylesheet to the document head. The stylesheet is always named `mes-loader-css`, and a stylesheet by the same name is removed prior to insertion, ensuring that there can only be one such sheet active at any given time. …
=> feat: generic loading dialog

mods/mag_instance_names/mag_instance_names.user.js, mods/user_instance_names/user_instance_names.user.js
Uses logic similar to the one in #446 to normalize usernames and suppress whitespace by using the link attributes instead of the innerText.
=> fix (user_instance_names): suppress whitespace

mods/hide_related/hide_related.js, mods/hide_related/hide_related.json
Resolves #428
Provides the option to hide related threads (crossposts) on the thread index, inside of threads, or both.
=> feat (hide related): hide related/crossposts area

mods/hide_logo/hide_logo.json, mods/hide_logo/hide_logo.user.js
Resolves #351, #392
- Add padding to magazine name when logo is empty
- Add Mbin logo (text and no-text versions)
- Support instances like fedia where there is no img and just a text span
=> fix (hide_logo) Add padding and support mbin logo

mods/hide_thumbs/hide_thumbs.json, mods/hide_thumbs/hide_thumbs.user.js
Resolves #394
Wraps raw inline thumbnails on microblogs with an image icon that can be used to toggle expand/hide. For thumbnails in threads and on the thread index, the user should prefer using the inbuilt settings sidebar.
=> fix (hide thumbs): apply on microblogs

kes.user.js, mods/omni/omni.user.js
Resolves #465. 
The MES MutationObserver previously watched for change to the entire HTML tree, which was necessary because Kbin provided a feature called "Turbo Mode" that would fetch remote content and load it in-place by rewriting the entire DOM. This feature no longer exists on Mbin (link navigation works in a standard fashion).
On Chromium-based browsers, `focus()` events were triggering an HTML mutation that produced false positives, causing MES to try to step through functions again. 
This PR drops this part of the mutation check.
=> fix: do not trigger on HTML mutation
