aclist/kbin-kes

megamod.user.js

Just a simple tweak that makes the tool and version number in the top right of the config modal into a link to here

Make version number into link to this repository

---

manifest.json
megamod.user.js
mods/easy-emoticon.user.js

Enables you to use various slash commands for emoticons. [Command guide here.](https://docs.google.com/document/d/1jMeY7GwmgwrV8mEC4jmkEKKWdKuWvjgLgYrtUS5hPYg/edit)

Easy Emoticon

---

manifest.json
megamod.user.js
mods/code-highlighting.user.js

Numerous edits around KCH. Biggest of which is updated to 0.4.2. Was able to get this working with the current iteration of megamod.

kbin-code-highlighting upgrade to 0.4.2 and load/unload functionality.

---

megamod.user.js

I accidentally left a little change I made for debugging in my pull request (setting the new version to 1.0 to force the update button to appear), this returns it to normal

fix: Replaced test version with actual version check

---

megamod.user.js

Just realized that the versionURL pointed to my fork instead of this repository, just fixed that and looked over everything again to make sure I didn't miss anything else

fix: Corrected link to version file

---

megamod.user.js

Just makes it easier to test upcoming changes by including the official kbin labs.

Add support for lab instances.

---

manifest.json
mods/improved-collapsible-comments.user.js

Just a few small tweaks to the collapsible comments mod

Add config option to collapsible comments, and prevent it from loading when there are no comments

---

kes.user.js
safegm.user.js

This breakout fix will allow mods to access safeGM.

Safegm breakout

---

kes.user.js

While implementing multi-author support (in an array), I changed some nearby items. I broke HTML strings into their JS counterparts to be more readable. I also made author links link to the current instance instead of kbin.social always.

Feature: Multiple author support

---

kes.user.js

Untested, but it should be the same as before.

Multi author support fix

---

kes.css
kes.user.js

For: https://github.com/aclist/kbin-kes/issues/101
* Changes the target of the event for opening settings menu.
* Changes style to more closely match kbin's style.
* Fixed wrench "jiggle" on hover.
VSC decided to reformat the css file. Sorry about that. For the review, no changes after line 16.

fix: wrench clickability and style

---

mods/kbin-federation-awareness.user.js

This will fix https://github.com/aclist/kbin-kes/issues/88 by being more specific with targeted CSS and adds additional margin for visibility purposes.

fix: kfa + cc

---

kes.user.js

Fixes https://github.com/aclist/kbin-kes/issues/90#issuecomment-1636403888
Note: My VSC likes to fix formatting. Sorry!

fix: update remaining paths for helpers

---

helpers/kes.css
kes.user.js

Changes li structure and uses CSS to make it non-invasive and position.
Note: CSS file seems to be spaced 5 or 6 by default, but my setting is 4.

fix: https://github.com/aclist/kbin-kes/issues/112

---

helpers/kes.css
kes.user.js

Revert "fix: https://github.com/aclist/kbin-kes/issues/112"

---

.eslintignore
.eslintrc.json
.gitignore
.prettierignore
.prettierrc.json
package.json

This is a basic setup for eslint and prettier. For VSC, you should have eslint and prettier installed. Using npm, it's just `npm install` while in the project directory.

Create basic eslint and prettier config

---

helpers/manifest.json
mods/nav-icons.user.js

I found the original font not very appealing, so this addition enables customization to both the font and the font weight.
Before: 
Now:
and many more fonts available
Video:
https://github.com/aclist/kbin-kes/assets/137783738/e189508e-47c5-47cd-9611-4e1e02f373c2

[Navbar icons as Text] Added font and font weight customization

---

mods/notifications-panel.user.js

Here's how it should look like right now
Because of Kbin's styling using `!important` (which I explained in #133) it doesn't work properly
Removing it from `padding` and `display` fixes it

[MOD] Notifications panel with async

---

helpers/kbin-mod-options.js

Implemented a basic fix for #357 using CSS nesting. All the styling for the menu now only applies to the actual menu.

[FIX] MES Settings Menu CSS now only applies in the actual menu

---

mods/expand_posts/expand_posts.json

Explicitly states that the mod does not work in mbin's compact view mode.

chore: reword JSON manifest (#368)

---

mods/clarify_recipient/clarify_recipient.user.js
mods/improved_collapsible_comments/improved_collapsible_comments.user.js

fix: collapsible comments

---

mods/user_instance_names/user_instance_names.user.js

fix: user instance names 2

---

mods/improved_collapsible_comments/improved_collapsible_comments.user.js

Resolves #395, works in conjunction with federation awareness mod as well

fix: padding on collapsed comments (#395)

---

mods/mail/mail.json
mods/mail/mail.user.js

fix: mail icon

---

mods/notifications_panel/notifications_panel.user.js

fix: invoke safeGM functions correctly

---

mods/nav_icons/nav_icons.json

Resolves https://github.com/aclist/kbin-kes/issues/411

fix: drop obsolete option from nav icons mod

---

mods/softblock/softblock.user.js

fix (softblock): do not trigger on crossposts

---

mods/rearrange/rearrange.user.js

fix: rearrange post order

---

mods/rearrange/rearrange.json
mods/rearrange/rearrange.user.js

fix (rearrange posts): support crosspost area

---

mods/mag_instance_names/mag_instance_names.user.js

fix: mag instance names

---

mods/hide_sidebar/hide_sidebar.json
mods/hide_sidebar/hide_sidebar.user.js

fix: suppress sidebar about card

---

mods/omni/omni.user.js

fix: omni keytrap

---

mods/improved_collapsible_comments/improved_collapsible_comments.user.js

fix (collapsible comments): handle alignment if user disabled avatars
